spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schoolorder?serverTimezone=GMT%2b8
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#端口号设置
server:
  ip: localhost #112.124.22.128
  port: 8888

mybatis:
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
  mapper-locations: classpath:mapper/*.xml #扫描.xml文件


files:
  upload:
    path: G:/project/java/files/
#     path: /home/files/